#!/bin/bash

clear
echo "Monitoring src/ for changes..."
echo -n "Hint: By default it runs tests."
echo "Pass 'r' to run the code"

case $1 in
  r) CMD="gleam run" ;;
  *) CMD="gleam test"  ;;
esac

inotifywait -q -m -r -e modify src test | while read -r _DIRECTORY EVENT _FILE; do
  # echo $DIRECTORY $EVENT $FILE
  case $EVENT in
    MODIFY*)
      clear
      echo "= ${CMD} ==============================="; echo
      ${CMD}
      echo; echo "= $(date) ==================="
      ;;
  esac
done
